### ISSUE TITLE
LSPD lack of inventory

### ISSUE THREAD

**Issue by Gr1dl0k** [D3monkat/PursuitXErrors#10]
We need med packs, defibrillators and taser cartriges.

**Comment by epicural** [comment]
Per Kat No no and NO,

**Comment by Gr1dl0k** [comment]
excuse me? first of all, please adress people with more respect. Also we at least need bandages. And yes we HAVE TO have taser cartriges. THINK PLEASE

**Comment by Gr1dl0k** [comment]
I dont need your attitude, and yes we need these...

**Comment by epicural** [comment]
I was in a Vc call with Kat when he told me to say that, and I wasn't given attitude I relaying what I heard from Kat to here which he said and I quote no to medpacks since there is an issue when non medics use the medpacks the person gets banned from the server and no to the defibrillators as something is in the works and no to taser cartriges because when you hit reload it will automatically reload so that is what I heard, If I gave an attitude I am sorry that wasnt my intention again was just relaying what was said which was no no and no

**Comment by Gr1dl0k** [comment]
all good friend, no worries im not upset it just felt like i got shot down lol
